# Generated by Django 2.2 on 2019-06-17 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20190617_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 17, 21, 31, 1, 829192), verbose_name='Date'),
        ),
    ]
